title: &title dear me
description: &description The easiest way to journal ever. We send a few texts a day. You answer. We add your instagram photos. You have a journal.

auth:
  username:
  password:

url: https://dearme.minond.xyz
survey_url: https://dearme.typeform.com/to/MYGOZG

worker:
  scheduler:
    range: 15 minutes
    interval: 5 minutes

social:
  image:

server:
  cookies: on
  session: on
  body_parsing: on
  robots_txt: off
  compression: on
  view_cache: on

manifest:
  name: *title
  short_name: *title
  description: *description
  start_url: /?utm_source=homescreen
  background_color: "#000"
  theme_color: "#000"
  display: standalone
  icons: []
    # - src:
    #   sizes:
    #   type:
