#!/bin/bash

sudo apt-get update

curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs build-essential

npm install -g yarn

git clone https://github.com/minond/dearme
